# SPDX-License-Identifier: GPL-3.0-or-later
"""
Linear-elastic FEA on a regular voxel grid.

8-node trilinear hexahedral elements, all identical in shape, so we build the
element stiffness matrix KE once and run a *matrix-free* conjugate-gradient
solve: K*u is evaluated element-by-element with vectorised numpy, never
assembling a global sparse matrix (keeps us scipy-free).

The solve is restricted to elements that actually exist (inside the build
space): only their nodes get DOFs, so empty margin around the part costs
nothing. All array work goes through the compute backend (``core.backend``):
the hosted edition's backend is pure numpy, while the optional GPU edition's
backend can route the same code onto a GPU array library. The maths is identical
either way.

DOF numbering (original/full space): node n has DOFs [3n, 3n+1, 3n+2].
Grid nodes: (nx+1)*(ny+1)*(nz+1) for an nx*ny*nz element grid.
"""

import numpy as np

from . import backend
from . import compute_plan


# ---------------------------------------------------------------------------
# Element stiffness matrix (unit cube, generated by Gauss quadrature)
# ---------------------------------------------------------------------------

def _hex8_KE(E=1.0, nu=0.3):
    """24x24 stiffness for a unit cube, isotropic material."""
    nodes = np.array([
        [-1, -1, -1], [1, -1, -1], [1, 1, -1], [-1, 1, -1],
        [-1, -1, 1], [1, -1, 1], [1, 1, 1], [-1, 1, 1],
    ], dtype=float)

    c = E / ((1 + nu) * (1 - 2 * nu))
    C = c * np.array([
        [1 - nu, nu, nu, 0, 0, 0],
        [nu, 1 - nu, nu, 0, 0, 0],
        [nu, nu, 1 - nu, 0, 0, 0],
        [0, 0, 0, (1 - 2 * nu) / 2, 0, 0],
        [0, 0, 0, 0, (1 - 2 * nu) / 2, 0],
        [0, 0, 0, 0, 0, (1 - 2 * nu) / 2],
    ])

    g = 1.0 / np.sqrt(3.0)
    gp = [-g, g]
    KE = np.zeros((24, 24))
    for xi in gp:
        for eta in gp:
            for zeta in gp:
                dN = np.zeros((3, 8))
                for i, (a, b, c_) in enumerate(nodes):
                    dN[0, i] = a * (1 + b * eta) * (1 + c_ * zeta) / 8.0
                    dN[1, i] = b * (1 + a * xi) * (1 + c_ * zeta) / 8.0
                    dN[2, i] = c_ * (1 + a * xi) * (1 + b * eta) / 8.0
                J = np.array([[0.5, 0, 0], [0, 0.5, 0], [0, 0, 0.5]])
                detJ = np.linalg.det(J)
                dNxyz = np.linalg.solve(J, dN)
                B = np.zeros((6, 24))
                for i in range(8):
                    bx, by, bz = dNxyz[:, i]
                    c0 = 3 * i
                    B[0, c0] = bx
                    B[1, c0 + 1] = by
                    B[2, c0 + 2] = bz
                    B[3, c0] = by
                    B[3, c0 + 1] = bx
                    B[4, c0 + 1] = bz
                    B[4, c0 + 2] = by
                    B[5, c0] = bz
                    B[5, c0 + 2] = bx
                KE += (B.T @ C @ B) * detJ
    return KE


# ---------------------------------------------------------------------------
# Element <-> global DOF connectivity
# ---------------------------------------------------------------------------

def _node_id(ix, iy, iz, nx, ny):
    return ix + (nx + 1) * (iy + (ny + 1) * iz)


def build_edof(nx, ny, nz):
    """Return edofMat [nelem, 24] of global DOF indices per element."""
    ex, ey, ez = np.meshgrid(
        np.arange(nx), np.arange(ny), np.arange(nz), indexing='ij')
    ex = ex.ravel()
    ey = ey.ravel()
    ez = ez.ravel()
    offs = [(0, 0, 0), (1, 0, 0), (1, 1, 0), (0, 1, 0),
            (0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]
    edof = np.empty((ex.size, 24), dtype=np.int64)
    for k, (ox, oy, oz) in enumerate(offs):
        nid = _node_id(ex + ox, ey + oy, ez + oz, nx, ny)
        edof[:, 3 * k] = 3 * nid
        edof[:, 3 * k + 1] = 3 * nid + 1
        edof[:, 3 * k + 2] = 3 * nid + 2
    return edof


# ---------------------------------------------------------------------------
# Matrix-free solver (restricted to active elements)
# ---------------------------------------------------------------------------

class VoxelFEA:
    """Solves K(rho) u = f matrix-free over the active (build-space) elements.

    active_elems : optional bool mask (nelem,). Only these elements - and the
    nodes they touch - enter the linear system, so empty space around the part
    is skipped entirely. The public API still speaks the full DOF space:
    solve() returns a full-length u and element_strain_energy() returns a full
    per-element array (zeros outside the active region).
    """

    def __init__(self, nx, ny, nz, nu=0.3, e_min=1e-9, active_elems=None,
                 compute_mode="AUTO", cpu_threads=0, verbose=False):
        self.nx, self.ny, self.nz = nx, ny, nz
        self.nelem = nx * ny * nz
        self.ndof_full = 3 * (nx + 1) * (ny + 1) * (nz + 1)
        self.e_min = e_min
        self.KE = _hex8_KE(E=1.0, nu=nu)
        self.edof_full = build_edof(nx, ny, nz)        # full, original DOFs

        if active_elems is None:
            self.active_elems = np.ones(self.nelem, dtype=bool)
        else:
            self.active_elems = np.asarray(active_elems, dtype=bool).ravel()

        # Compress to the DOFs actually used by active elements.
        edof_a = self.edof_full[self.active_elems]      # (na, 24) original DOFs
        used = np.unique(edof_a)
        remap = -np.ones(self.ndof_full, dtype=np.int64)
        remap[used] = np.arange(used.size)
        self.used_dofs = used
        self.remap = remap
        self.ndof = int(used.size)                       # reduced size
        self.edof = remap[edof_a]                        # (na, 24) reduced DOFs

        self.free = None
        self._diag = None
        self.verbose = verbose

        # Decide CPU / single-GPU / multi-GPU / multi-process-CPU for this
        # grid's actual (reduced) DOF count -- see core/compute_plan.py for
        # the thresholds. When the plan is "parallel" (multi_gpu/multi_cpu),
        # the hot gather-matmul-scatter in _apply_K/_diagonal is delegated to
        # a pool and the surrounding CG vector ops stay on host numpy (they
        # are O(ndof), cheap, and the pool already hands back host arrays).
        self.plan = compute_plan.choose(self.ndof, mode=compute_mode,
                                        cpu_threads=cpu_threads,
                                        verbose=verbose)
        self._pool = None
        self.xp = np if self.plan.parallel else self.plan.xp
        self._init_pool()
        self.KE_x = self.xp.asarray(self.KE)
        self.edof_x = self.xp.asarray(self.edof)

    def _init_pool(self):
        """Build the multi-worker matvec pool if the plan calls for one,
        falling back one rung (multi_gpu -> gpu -> cpu, multi_cpu -> cpu) if
        it fails to construct for any reason -- a failed accelerator must
        never abort the solve, only make it slower."""
        plan = self.plan
        if plan.kind == "multi_cpu":
            from . import parallel_cpu
            try:
                self._pool = parallel_cpu.CPUMatVecPool(
                    self.edof, self.KE, self.ndof, plan.n_workers,
                    verbose=self.verbose)
                return
            except Exception as exc:
                if self.verbose:
                    print(f"[Blendtopo] multi-CPU pool unavailable ({exc}); "
                          f"falling back to single-process CPU")
                self.plan = compute_plan.ComputePlan(
                    "cpu", np, 1, "CPU (multi-CPU fallback)")
                self.xp = np
        elif plan.kind == "multi_gpu":
            from . import parallel_gpu
            try:
                self._pool = parallel_gpu.GPUMatVecPool(
                    self.edof, self.KE, self.ndof, plan.n_workers,
                    verbose=self.verbose)
                return
            except Exception as exc:
                if self.verbose:
                    print(f"[Blendtopo] multi-GPU pool unavailable ({exc}); "
                          f"falling back to single GPU/CPU")
                self.plan = compute_plan.choose(
                    self.ndof, mode="GPU", verbose=self.verbose)
                self.xp = self.plan.xp

    def close(self):
        """Release the matvec pool's workers/devices, if any were started."""
        if self._pool is not None:
            try:
                self._pool.close()
            except Exception:
                pass
            self._pool = None

    def set_fixed(self, fixed_dofs):
        """fixed_dofs: original global DOF indices to constrain."""
        free = np.ones(self.ndof, dtype=bool)
        fd = self.remap[np.asarray(fixed_dofs, dtype=np.int64)]
        fd = fd[fd >= 0]
        free[fd] = False
        self.free = free

    def _Evec_active(self, Evec_full):
        return np.asarray(Evec_full, dtype=float)[self.active_elems]

    def _apply_K(self, u, Evec_a):
        # BLAS matmul (KE is symmetric) then a bincount scatter-add. The numpy
        # and GPU array modules share these semantics, so one path runs on both.
        # When a multi-CPU/multi-GPU pool is active this whole gather-matmul-
        # scatter is delegated to it instead (see core/parallel_cpu(_gpu).py).
        if self._pool is not None:
            return backend.asnumpy(self.xp.asarray(
                self._pool.apply(backend.asnumpy(u))))
        xp = self.xp
        ue = u[self.edof_x]                                  # (na, 24)
        ke_ue = (ue @ self.KE_x.T) * Evec_a[:, None]
        return xp.bincount(self.edof_x.ravel(),
                           weights=ke_ue.ravel(), minlength=self.ndof)

    def _diagonal(self, Evec_a):
        xp = self.xp
        if self._pool is not None:
            d = self.xp.asarray(self._pool.diagonal())
        else:
            diagKE = xp.diag(self.KE_x)
            contrib = Evec_a[:, None] * diagKE[None, :]          # (na, 24)
            d = xp.bincount(self.edof_x.ravel(),
                            weights=contrib.ravel(), minlength=self.ndof)
        d = xp.where(d == 0, 1.0, d)
        return d

    def solve(self, Evec, f, tol=1e-4, max_cg=None, x0=None):
        """Preconditioned CG over active DOFs. Returns full-length u (numpy).

        x0 : optional warm-start (full-length numpy) - hugely cuts CG iters
        because the structure changes only slightly between SIMP steps.
        """
        if self.free is None:
            raise RuntimeError("call set_fixed() before solve()")
        xp = self.xp
        free = xp.asarray(self.free)
        Evec_a = xp.asarray(self._Evec_active(Evec))
        if self._pool is not None:
            self._pool.set_density(backend.asnumpy(Evec_a))
        f_r = xp.asarray(np.asarray(f, dtype=float)[self.used_dofs])

        self._diag = self._diagonal(Evec_a)
        Minv = 1.0 / self._diag

        if x0 is None:
            u = xp.zeros(self.ndof)
            r = f_r.copy()
        else:
            u = xp.asarray(np.asarray(x0, dtype=float)[self.used_dofs])
            u = xp.where(free, u, 0.0)
            r = f_r - self._apply_K(u, Evec_a)
        r = xp.where(free, r, 0.0)

        z = xp.where(free, Minv * r, 0.0)
        p = z.copy()
        rz = float(r @ z)

        fnorm = float(xp.linalg.norm(xp.where(free, f_r, 0.0)))
        if fnorm == 0:
            return np.zeros(self.ndof_full)
        max_cg = max_cg or 4 * int(self.free.sum())

        for _ in range(max_cg):
            Kp = self._apply_K(p, Evec_a)
            Kp = xp.where(free, Kp, 0.0)
            alpha = rz / float(p @ Kp)
            u = u + alpha * p
            r = r - alpha * Kp
            if float(xp.linalg.norm(xp.where(free, r, 0.0))) / fnorm < tol:
                break
            z = xp.where(free, Minv * r, 0.0)
            rz_new = float(r @ z)
            p = z + (rz_new / rz) * p
            p = xp.where(free, p, 0.0)
            rz = rz_new

        u = xp.where(free, u, 0.0)
        u_full = np.zeros(self.ndof_full)
        u_full[self.used_dofs] = backend.asnumpy(u)
        return u_full

    def element_strain_energy(self, u_full):
        """Per-element u_e^T KE u_e for ALL elements (numpy, length nelem)."""
        u = np.asarray(u_full)
        ce = np.zeros(self.nelem)
        ue = u[self.edof_full[self.active_elems]]
        ke_ue = ue @ self.KE.T
        ce[self.active_elems] = np.einsum('ei,ei->e', ue, ke_ue)
        return ce
